version: '3'

services:

  db:
    image: postgres:alpine
    volumes:
      - ./.docker/volumes/db:/var/lib/postgresql/data
  
  web:
    build: .
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db